pom update
- NoSuchMethodError was being thrown during test suite execution
of projects because the junit version used by the test suite
was more recent that the one required by the pom file. now the
pom file adds the dependency for the latest junit and it appears
first in the list of dependencies so it cannot be overridden